package com.shopping.exception;

public enum ErrorCode {

	SHOPPING_APPLICATION_100,
	SHOPPING_DATABASE_100,
	SHOPPING_DATABASE_101,
	SHOPPING_VALIDATION_100,
	SHOPPING_VALIDATION_101,
	SHOPPING_BUSINESS_100,

}
