
create table product(
   RECORD_ID VARCHAR(36) NOT NULL ,
   NAME VARCHAR(30) NOT NULL,
   QUANTITY INT NOT NULL,
   PRICE DECIMAL(7,2) NOT NULL,
   SKU VARCHAR(30) NOT NULL,
   DEPARTMENT_ID varchar(36),
   DESCRIPTION varchar(250),
   PRIMARY KEY (RECORD_ID)
   
);

create table department(
	RECORD_ID VARCHAR(36) NOT NULL PRIMARY KEY ,
	DEPARTMENT_NAME VARCHAR(30),
	DESCRIPTION VARCHAR(250)
	);
	