INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());


INSERT INTO DEPARTMENT(DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
