
create table product(
   ID BIGINT AUTO_INCREMENT ,
   NAME VARCHAR(30) NOT NULL,
   QUANTITY INT NOT NULL,
   PRICE DECIMAL(7,2) NOT NULL,
   SKU VARCHAR(30) NOT NULL,
   DEPARTMENT_ID varchar(36),
   DESCRIPTION varchar(250),
   CREATED_BY  VARCHAR(30),
   CREATED_DATE DATE,
   MODIFIED_BY  VARCHAR(30),
   MODIFIED_DATE DATE
   
   
);


create table department(
	ID BIGINT AUTO_INCREMENT ,
	DEPARTMENT_NAME VARCHAR(30),
	DESCRIPTION VARCHAR(250),
	CREATED_BY  VARCHAR(30),
	CREATED_DATE DATE,
	MODIFIED_BY  VARCHAR(30),
	MODIFIED_DATE DATE
	);

	