INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID) VALUES ('gshdgkuawrtwq7q6576','Book',90,100,'00B',20);
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID) VALUES ('ytu5683746etfayufgya','Book',90,100,'00B',20);
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID) VALUES ('twutrq7e6537trugf','Book',90,100,'00B',20);
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID) VALUES ('yegudgy7ie6tewygda','Book',90,100,'00B',20);
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID) VALUES ('vgzhjgeaukt676tgvd','Book',90,100,'00B',20);

INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION) VALUES ('hfzjdgfdkuyfguw7r6868r8','HOME','HOME APPLIANCES');
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION) VALUES ('yreutiewti76534tgje','HOME','HOME APPLIANCES');
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION) VALUES ('dhdgfy756877ysfgd','HOME','HOME APPLIANCES');
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION) VALUES ('cbshyuw6765','HOME','HOME APPLIANCES');
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION) VALUES ('fhsgueytr7w464ty','HOME','HOME APPLIANCES');
