
create table product(
   ID BIGINT NOT NULL AUTO_INCREMENT ,
   NAME VARCHAR(30) UNIQUE NOT NULL,
   QUANTITY INT NOT NULL,
   PRICE DECIMAL(7,2) NOT NULL,
   SKU VARCHAR(30) NOT NULL,
   DEPARTMENT_ID INT NOT NULL,
   DESCRIPTION VARCHAR(250),
   CREATED_BY  VARCHAR(30) NOT NULL,
   CREATED_DATE DATE,
   MODIFIED_BY  VARCHAR(30) NOT NULL,
   MODIFIED_DATE DATE
   
   
);


create table department(
	ID BIGINT NOT NULL AUTO_INCREMENT  ,
	DEPARTMENT_NAME VARCHAR(30) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(250),
	CREATED_BY  VARCHAR(30) NOT NULL,
	CREATED_DATE DATE,
	MODIFIED_BY  VARCHAR(30) NOT NULL,
	MODIFIED_DATE DATE
	);

	