INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('gshdgkuawrtwq7q6576','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('ytu5683746etfayufgya','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('twutrq7e6537trugf','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('bsjkghoaite8te8gd','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('hfdguktututgbx8w758','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('hvdsgrt735634756etvxbc','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('vsdhgfdsyu6r7865','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());
INSERT INTO PRODUCT (RECORD_ID,NAME, QUANTITY,PRICE,SKU,DEPARTMENT_ID,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('xsvchsgfdur67835','Book',90,100,'00B',20,'Stationary','Jill',NOW(),'Jill',NOW());


INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('hfzjdgfdkuyfguw7r6868r8','HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('yreutiewti76534tgje','HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('dhdgfy756877ysfgd','HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('cbshyuw6765','HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
INSERT INTO DEPARTMENT(RECORD_ID,DEPARTMENT_NAME,DESCRIPTION,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) VALUES ('fhsgueytr7w464ty','HOME','HOME APPLIANCES','Jill',NOW(),'Jill',NOW());
